### PR TITLE
Allow both interactive and non-interactive usage of Docker image #69

### PR DESCRIPTION
**Pull request by kelson42**

### CODE REVIEW

**Comment by kelson42** [comment]
Per default it works like before. But if you want to execute a script just run:
`docker run -t mwoffliner -c cmd1 && cmd2 && cmd3`

**Comment by automactic** [comment]
I shouldn't be the reviewer of this. I am not familiar with this project and have no idea how changing the docker file could impact other parts of the project.

It looks good. But I am not sure if you still could pass params to mwoffliner in this way. And what does `CMD["-I"]` do?

**Comment by automactic** [comment]
Have you tested this? I don't think it works. 

If I am understanding docker correctly, things after `mwoffliner `, which I presume is the image name, will be passed to `bin/bash`, along with `--init`. It will just print out error, since `bin/bash` does not understand `-c`.

I could be wrong though. I will update `openzim/mwoffliner` and test to see if it works

**Comment by automactic** [comment]
OK, I just tried it. So if you run `docker run -t openzim/mwoffliner -c --mwUrl=https://bm.wikipedia.org/`, you are gonna get:
```
/bin/bash: --: invalid option
Usage:	/bin/bash [GNU long option] [option] ...
/bin/bash [GNU long option] [option] script-file ...
[omitted]
```

**Comment by kelson42** [comment]
docker run -t openzim/mwoffliner -c "mwoffliner ...." will work

**Pull request merged**
