### PR TITLE
Create debugging advice for new contributors

### PR DESCRIPTION
**Pull request by bradyhunsaker**
@kelson42 This is background and advice that would have been helpful to me when I was first starting on mwoffliner bugs.

Of course, feel free to change the name and edit as much as you like.  I couldn't find any naming convention for this sort of advice.

### CODE REVIEW

**Comment by ISNIT0** [comment]
Might also be worth mentioning `--format=nozim` and `--articleList`?

**Comment by kelson42** [comment]
@ISNIT0 We need to be careful about not repeating `--help`

**Comment by ISNIT0** [comment]
Agreed, but those two specifically are really handy for debugging (I don't have a working copy of zimwriterfs on my Mac, and don't want to download entire wikis :))

**Comment by kelson42** [comment]
@ISNIT0 You are perfectly right. That is a good idea.

**Comment by bradyhunsaker** [comment]
OK, I'll edit the change in the next day or two based on the feedback from
both of you.

**Comment by bradyhunsaker** [comment]
Changes made.  Please take another look.

**Comment by ISNIT0** [comment]
LGTM 🎉

**Pull request merged**
