### PR TITLE
:bug: fix article list homepage links to articles with '/' (#911)

### LINKED ISSUE #911: Slashes in URL are not encoded properly on welcome page
Juste mirroring "User:Kelson/MWoffliner_CI_reference" on WPEN and then having a list of one item in the welcome page. Unfortunately the link has the slashes encoded.. so the content is then not displayed properly.

### PR DESCRIPTION
**Pull request by ISNIT0**
Closes #911

### CODE REVIEW

**Comment by kelson42** [comment]
@ISNIT0 This still does not work, the code is:
```
<a href="User%3AKelson%2FMWoffliner_CI_reference">User:Kelson/MWoffliner CI reference</a>
```

and it should be
```
<a href="User%3AKelson/MWoffliner_CI_reference">User:Kelson/MWoffliner CI reference</a>
```

URL writing and rewriting is not robust. It is not because the code responsible of it is not abstracted and not automated tested. This is exactly what I was complaining about a few days ago in #904 because of other URL related problems.

**Comment by ISNIT0** [comment]
Are you sure that's the right branch? I'm getting: 
image

**Comment by kelson42** [comment]
@ISNIT0 I will test again.

**Comment by kelson42** [comment]
@ISNIT0 Seems indeed to work now :)

**Pull request merged**
