### PR TITLE
Don't mirror 'Story' namespace

### LINKED ISSUE #1853: Unable to scrape id.wikipedia.org anymore
The problem is with articles in the « Story » namespace. Like for https://id.wikipedia.org/wiki/Story:Satelit_Oberon

### PR DESCRIPTION
**Pull request by kelson42**
Introduces the concept of namespace blacklist for this.

Fixes  #1853

### CODE REVIEW

**Comment by kelson42** [comment]
@VadimKovalenkoSNF I have the feeling the failing test has nothing to do with this PR. Do you confirm?

**Comment by kelson42** [comment]
@VadimKovalenkoSNF seems to woek now !?!

**Comment by VadimKovalenkoSNF** [comment]
@kelson42 Yes, but I suspect that something is wrong with the pipeline. I got similar test issues that appeared today in other PRs.

**Comment by VadimKovalenkoSNF** [comment]
I made a few changes and added tests for the blacklisted namespace.

**Pull request merged**
