### PR TITLE
Batch wikilinks redis requests on article parsing

### LINKED ISSUE #1718: Batch isMirrored redis requests on article parsing
When an article is parsed, every single wikilink within the article checks if the linked article is going to be parsed too and available in [isMirrored](https://github.com/openzim/mwoffliner/blob/main/src/util/rewriteUrls.ts#L16), which gets sequentially awaited.

I checked how big the impact is, and on parsing the 19.577 articles of the [pokemon wiki](https://pokemon.fandom.com) i got 2.685.074 wikilinks, spending 53min17s awaiting redis HGET.
A basic improvement would be to batch the requests per article and filter out duplicates.
It's impossible to say how much the performance impact will be, since we are in workers waiting for network requests, but it's well worth it to try.

(follow up to what what i raised in a comment in  https://github.com/openzim/mwoffliner/issues/1176#issuecomment-1372409102)

### PR DESCRIPTION
**Pull request by uriesk**
Instead of checking every wikilink one-by-one if it is going to be fetched, batch all links of an article together.
Use `HEXISTS` instead of `HGET` for checking the existence of a field.

I did some basic benchmarks with smaller wikis and it is about 5% faster at article scrapping phase. I think only the zimfarm on larger wikis can tell us the actual impact.

closes #1718

### CODE REVIEW

**Comment by kelson42** [comment]
@uriesk 5% is quite good actually. Don't forget to remove draft when you are so far.

**Comment by uriesk** [comment]
@kelson42 i was hoping for more. It's hard to benchmark because the bandwidth fluctuates by more than those 5%

got a question
When a redirect gets found, it links to the original, it was the same in the old code.
new:
https://github.com/uriesk/mwoffliner/blob/pipelining/src/util/rewriteUrls.ts#L247
old:
https://github.com/openzim/mwoffliner/blob/main/src/util/rewriteUrls.ts#L24
This is deliberately, right?

**Comment by uriesk** [comment]
This looks good now.
I hope we can try a larger wiki with the zimfarm with those changes soon and see if things improved :)

**Review by kelson42 — APPROVED** [review]
I have made made a superficial review. It seems to work but I see no speedup at all. That said, the principle is better. I think, and this would be something additional, that each function would be nefit of a small comment explaining what it does, in particular `rewriteUrlNoArticleCheck()`.

Quite a bit of code has been moved/changed, just hope that nothing fondamental in the link treatment has been changed. That only the architecturing has changed.

If OK for @pavel-karatsiuba, I would merge it and give it a try, but don't really expect much impact anyway.

**Comment by uriesk** [comment]
Thought so.
I am running it in  an environment with limited CPU speed but good bandwidth and have to time the article downloading phase specifically to see a tiny improvement.

That being said, spaming less requests to redis is always a good idea and it's one potential issue out of the way.

`rewriteUrlNoArticleCheck()` is the same as `rewriteURL` was before, just some ifs flattened, mediaDependencies in the arguments and wikilink parsing at the end moved out.
I can do elaborate comments when the switch to eslint is happening. There is lots of potential refactoring going to happen, with how touchy eslint can be.

**Comment by kelson42** [comment]
@pavel-karatsiuba works on #1699 which should be ready very soon.

**Review by pavel-karatsiuba — APPROVED** [review]

**Pull request merged**
