### PR TITLE
:white_check_mark: MWApi and URLRewriting tests

### PR DESCRIPTION
**Pull request by ISNIT0**
@kelson42 I think this covers your requests here: https://github.com/openzim/mwoffliner/pull/847

### CODE REVIEW

**Comment by kelson42** [comment]
@ISNIT0 Please make one PR for one Ticket, otherwise this is really complicated.

**Comment by ISNIT0** [comment]
@kelson42 The paragraph removal commit was cherry-picked into a lot of PRs to fix some broken tests

**Comment by kelson42** [comment]
@ISNIT0 Please rebase on master. This PR includes code of other feature branches.

**Comment by kelson42** [comment]
@ISNIT0 Please never do so because it makes everything complicated to understand. If you need this git commit in other branches, then merge this PR to master and rebase the other features branches properly on master afterward.

**Comment by ISNIT0** [comment]
@kelson42 Can this be merged?

**Pull request merged**
