### PR TITLE
Setting title for main page

### LINKED ISSUE #1022: Set proper page title to selection welcome page
It is currently `<title></title>`, it should be the title of the ZIM file.

### PR DESCRIPTION
**Pull request by bakshiutkarsha**
should resolve #1022

### CODE REVIEW

**Comment by kelson42** [comment]
@audiodude There is a trailing space again.

**Comment by bakshiutkarsha** [comment]
> @audiodude There is a trailing space again but this is the kind of code I expected. That said, please secure the whole stuff is HTML encoded properly.

Will add the encoding and respective test-cases as well.

**Comment by audiodude** [comment]
I assume I was mentioned by accident?

**Comment by kelson42** [comment]
> I assume I was mentioned by accident?

@audiodude This is an error indeed. Sorry about that.

**Pull request merged**
