### PR TITLE
Code simplification

### LINKED ISSUE #1122: Simplify mw-api.ts
I see a lot of code simplification potential in `mw-api.ts`, at least:
* use `splice` to go through lists in chunk
* stop global variable
* remove duplicate codes
* `mwRetToArticleDetail` should be deleted and used directly in `downloader`.
* stop using old `mapLimit`.
* ...

### PR DESCRIPTION
**Pull request by kelson42**
Fixes #1122

### CODE REVIEW

**Comment by bakshiutkarsha** [comment]
@midik I will take up the review by EOD.

**Comment by kelson42** [comment]
@midik Please rebase (always!) on `master`.

**Comment by kelson42** [comment]
@midik Seems buggy to me:
```
$ rm -rf out/ && time ./node_modules/.bin/ts-node ./src/cli.ts --mwUrl=https://en.wikipedia.org --articleList="https://download.openzim.org/wp1/enwiki_2020-04/tops/100.tsv" --adminEmail="kelson@kiwix.org" --optimisationCacheUrl="http://s3.us-west-1.wasabisys.com/?bucketName=org-kiwix-dev-mwoffliner&keyId=6JEDKJFH5Z3HDF3L3KH6&secretAccessKey=m2vQMjnneDjnrYztjfHrAUKneIf0SNGt75k9iITm"  --osTmpDir=/dev/shm --verbose
[log] [2020-05-28T07:33:06.394Z] Starting mwoffliner v1.10.8...
(node:1009796) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
[log] [2020-05-28T07:33:07.232Z] Successfully logged in S3
[log] [2020-05-28T07:33:07.234Z] Getting text direction...
[log] [2020-05-28T07:33:07.235Z] Getting site info...
[log] [2020-05-28T07:33:07.235Z] Getting sub-title...
[info] [2020-05-28T07:33:07.236Z] Downloading [https://en.wikipedia.org/wiki/]
[info] [2020-05-28T07:33:07.237Z] Downloading [https://en.wikipedia.org/wiki/]
[log] [2020-05-28T07:33:07.403Z] Text direction is [ltr]
[log] [2020-05-28T07:33:08.173Z] Using REST API
[log] [2020-05-28T07:33:08.331Z] Using output directory /home/kelson/code/mwoffliner/out
[info] [2020-05-28T07:33:08.332Z] Creating temporary directory [/dev/shm/mwoffliner-1590651188332]
[log] [2020-05-28T07:33:08.334Z] Using temporary directory /dev/shm/mwoffliner-1590651188332
[log] [2020-05-28T07:33:08.335Z] Downloading article list from [https://download.openzim.org/wp1/enwiki_2020-04/tops/100.tsv] to [/dev/shm/mwoffliner-1590651188332/100.tsv]
[info] [2020-05-28T07:33:08.485Z] ArticleList has [100] items
[info] [2020-05-28T07:33:08.646Z] Getting article ids
[log] [2020-05-28T07:33:08.648Z] Worker [0] getting article range [0-100] of [100] [100%]
[log] [2020-05-28T07:33:08.818Z] Got error from MW Query undefined
[log] [2020-05-28T07:33:08.835Z] Total articles found in Redis  100
[log] [2020-05-28T07:33:08.836Z] Doing dump
[log] [2020-05-28T07:33:08.837Z] Writing zim to [/home/kelson/code/mwoffliner/out/wikipedia_en_100_2020-05.zim]
[log] [2020-05-28T07:33:08.837Z] Flushing Redis file store
[info] [2020-05-28T07:33:08.888Z] Copying Static Resource Files
[info] [2020-05-28T07:33:08.894Z] Finding stylesheets to download
[info] [2020-05-28T07:33:08.895Z] Downloading [https://en.wikipedia.org/wiki/]
[log] [2020-05-28T07:33:09.205Z] Found [3] stylesheets to download
[log] [2020-05-28T07:33:09.205Z] Downloading stylesheets and populating media queue
[info] [2020-05-28T07:33:09.215Z] Downloading CSS from https://en.wikipedia.org/w/load.php?lang=en&modules=ext.uls.interlanguage|ext.visualEditor.desktopArticleTarget.noscript|ext.wikimediaBadges|skins.vector.styles.legacy&only=styles&skin=vector
[info] [2020-05-28T07:33:09.216Z] Downloading CSS from https://en.wikipedia.org/w/load.php?lang=en&modules=site.styles&only=styles&skin=vector
[info] [2020-05-28T07:33:09.216Z] Downloading CSS from https://en.wikipedia.org/w/index.php?title=Mediawiki:offline.css&action=raw
[info] [2020-05-28T07:33:09.216Z] Downloading [https://en.wikipedia.org/w/load.php?lang=en&modules=ext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cskins.vector.styles.legacy&only=styles&skin=vector]
[info] [2020-05-28T07:33:09.216Z] Downloading [https://en.wikipedia.org/w/load.php?lang=en&modules=site.styles&only=styles&skin=vector]
[info] [2020-05-28T07:33:09.217Z] Downloading [https://en.wikipedia.org/w/index.php?title=Mediawiki:offline.css&action=raw]
[log] [2020-05-28T07:33:09.390Z] Downloaded stylesheets
[log] [2020-05-28T07:33:09.391Z] Saving favicon.png...
[info] [2020-05-28T07:33:09.559Z] Downloading [http://en.wikipedia.org/static/images/project-logos/enwiki.png]
[log] [2020-05-28T07:33:10.223Z] Updating article thumbnails for articles
[log] [2020-05-28T07:33:10.230Z] Getting Main Page
[log] [2020-05-28T07:33:10.230Z] Creating main page...
[log] [2020-05-28T07:33:10.241Z] Getting articles
[info] [2020-05-28T07:33:10.247Z] Worker [0] processing batch of article ids [["Arthropod","+98 more +","Karnataka"]]
[info] [2020-05-28T07:33:10.248Z] Getting article [Arthropod] from https://en.wikipedia.org/api/rest_v1/page/mobile-sections/Arthropod
[warn] [2020-05-28T07:33:10.377Z] Failed to get article [Arthropod] using remote Parsoid, trying with local one TypeError: Cannot read property 'subCategories' of null
    at /home/kelson/code/mwoffliner/src/util/articleRenderers.ts:36:76
    at Generator.next (<anonymous>)
    at fulfilled (/home/kelson/code/mwoffliner/src/util/articleRenderers.ts:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[info] [2020-05-28T07:33:10.389Z] Getting article [Arthropod] from https://en.wikipedia.org/w/api.php?action=visualeditor&mobileformat=html&format=json&paction=parse&page=Arthropod
[warn] [2020-05-28T07:33:11.467Z] Error downloading article [Arthropod], skipping TypeError: Cannot read property 'title' of null
    at injectHeader (/home/kelson/code/mwoffliner/src/util/articleRenderers.ts:81:57)
    at renderDesktopArticle (/home/kelson/code/mwoffliner/src/util/articleRenderers.ts:92:57)
    at /home/kelson/code/mwoffliner/src/util/articleRenderers.ts:23:22
    at Generator.next (<anonymous>)
    at fulfilled (/home/kelson/code/mwoffliner/src/util/articleRenderers.ts:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[info] [2020-05-28T07:33:11.468Z] Getting article [Enzyme] from https://en.wikipedia.org/api/rest_v1/page/mobile-sections/Enzyme
[warn] [2020-05-28T07:33:11.583Z] Failed to get article [Enzyme] using remote Parsoid, trying with local one TypeError: Cannot read property 'subCategories' of null
    at /home/kelson/code/mwoffliner/src/util/articleRenderers.ts:36:76
    at Generator.next (<anonymous>)
    at fulfilled (/home/kelson/code/mwoffliner/src/util/articleRenderers.ts:5:58)
```

**Comment by bakshiutkarsha** [comment]
> --osTmpDir=/dev/shm --verbose

Same issue is happening for me.

**Comment by midik** [comment]
Fixed in #1138.
[Proof](https://github.com/openzim/mwoffliner/files/4719283/wpen-100.log).

**Comment by kelson42** [comment]
@midik If this PR is depending on an other PR to work well, then please rebase on that branch.

**Comment by midik** [comment]
@kelson42 they're independent except that both intended to make the code better ;)

**Pull request closed without merging**
