### PR TITLE
Reflowing mwOffliner for current standards.

### PR DESCRIPTION
**Pull request by darkenvy**
using AirBNB's style guide, I have imported a eslint file as well. I have started to parse out the main mwoffliner js file and fix small problems. I wanted to get this up and merged so Subbu has something to work with (primarily the eslint.json file).

### CODE REVIEW

**Comment by kelson42** [comment]
@subbuss If you have any feedback about these commits.

**Comment by darkenvy** [comment]
Subbu and I are going to contribute in a fork. Closing this PR.

**Comment by kelson42** [comment]
@darkenvy What is the added value in comparison to working on a PR or even a branch of the official repo?

**Comment by subbuss** [comment]
Greetings from Minneapolis!

@kelson42, on github, forks are very common for developing some code on the side and then merging it back. I don't see a real functional difference between forks and branches for developers who are not core members of the repo.

That said, I think @darkenvy meant a branch of this official repo because we discussed working on the refactor branch of this repo, not a fork.

**Comment by subbuss** [comment]
Otherwise, besides those two minor comments, I think this PR is good to go (in the branch, and after testing, can be merged back into master)! 

eslint and npm-shrinkwrap.json was on my list of things to do. But, package-lock.json is even better (after I read about what the differences between the two are). Thanks for the fixes. Good cleanup.

**Comment by kelson42** [comment]
@subbuss thx for the explanation and its great to work on an official repo branch.
@darkenvy Congrats for what I think might be your first merged commits (sorry if this is the second one) :)

**Pull request closed without merging**
