### PR TITLE
corrected uri in parsoid

### LINKED ISSUE #1461: MWoffliner only picks up landing page
I ran a [chabadpedia](https://farm.openzim.org/pipeline/0870e3084c6327bb4e7f8906) recipe which landed a zim file after a few minutes without apparent incident. 

It appears however than none of the frontpage links (though they appear as hyperlink) is clickable, and that only that page was in fact scraped. Clicking on links leads to no apparent action, and the zim file is only 1.17 Mb. From the log, it looks like all links returned a 404.

### PR DESCRIPTION
**Pull request by MananJethwani**
@kelson42 this fixes #1461.
sorry, I don't know how I missed this.

### CODE REVIEW

**Review by kelson42 — CHANGES_REQUESTED** [review]
Looks good, but the CI does not pass.

But it does not pass on git master either, locally I have this error:
```
  extracting title from href

    ✔ Title with hrefs contaning /wiki
    ✔ Title with relative path
    ✔ Title with two dir path
    ✔ Title with Anchor Jump
    ✔ Interwiki title
    Closing all redis connections
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mwoffliner@1.11.5 tape: `tape -r tsconfig-paths/register -r ts-node/register "test/unit/bootstrap.test.ts" "test/unit/downloader.test.ts" "test/unit/dump.test.ts" "test/unit/mwApi.test.ts" "test/unit/redis.test.ts" "test/unit/s3.test.ts" "test/unit/sanity.test.ts" "test/unit/saveArticles.test.ts" "test/unit/styles.test.ts" "test/unit/urlRewriting.test.ts" "test/unit/util.test.ts" "test/unit/webpAndRedirection.test.ts"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mwoffliner@1.11.5 tape script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kelson/.npm/_logs/2021-05-14T09_03_31_933Z-debug.log



  Failed Tests: There was 1 failure

    MWApi Article Ids

      ✖ Article "United_Kingdom" has categories
```

Might be that something has changed upstream and we need to adapt our test. Would you be able to do that in this PR please?

**Comment by MananJethwani** [comment]
@kelson42 the test fails here due to other reason there is some problem in installation as well if you look at checks in this PR.
I will try to resolve it asap.

**Comment by kelson42** [comment]
Unfortunately the CI refuses to pass.

**Comment by MananJethwani** [comment]
@kelson42 the CI fails because of an indirect dependency `merge` which is not present.
steps to reproduce are simple you need to clone the repository again and just use `npm ci` then when you run `npm run test`
you can see the exact same error.
this is an indirect dependency so looks to me like an upstream bug.

**Comment by kelson42** [comment]
@MananJethwani The dependences are fixed and it was not there a few days ago at the release tune... so i wonder about which bug exactly you talk about?

**Comment by MananJethwani** [comment]
@kelson42 I am talking about the error you see in CI `Error: Cannot find module 'merge'`
merge is an indirect dependency....it is used by `kad` which is used by `parsoid`.

**Comment by MananJethwani** [comment]
@kelson42 I have updated local-parsoid test but it brings back #1278 sadly.

**Pull request closed without merging**
