### PR TITLE
added white stroke for transparent png in dark mode

### PR DESCRIPTION
**Pull request by MananJethwani**
this solves the issue #1026 
@kelson42 here is the zim file after applying white stroke

img2

### CODE REVIEW

**Review by kelson42 — CHANGES_REQUESTED** [review]
Really elegant hacky solution. Hopefully we won’t discover any bad side effects. Have made a few remarks directly on Slack to polish the solution.

Ping @Jaifroid and @automactic as wll as they might be interestto have a look as well to this PR.

**Review by kelson42 — CHANGES_REQUESTED** [review]
@MananJethwani This looks good from the principle, please provide a demo ZIM file to we can all test if it works fine. Please provide one before the fix and one with the fix, so we can see the difference.

**Comment by MananJethwani** [comment]
@kelson42 give me some time I found a bug solving it first

**Comment by MananJethwani** [comment]
[issue_1026.zip](https://github.com/openzim/mwoffliner/files/5402620/issue_1026.zip)
here are the files before and after applying white stroke to images
@kelson42  I had to add an inversion to cancel out the inversion applied by drop-shadow effect which inverted few images

**Comment by MananJethwani** [comment]
@Jaifroid and @automactic did you have a look at zip file mentioned above is it fine?

**Review by kelson42 — CHANGES_REQUESTED** [review]
Firefox normal mode:
image

Firefox dark mode:
image

This PR does not work.

**Comment by kelson42** [comment]
@MananJethwani I don't believe this problem is solveable easily. Was an error to tag itt as "good-first-issue", sorry.

**Pull request closed without merging**
