### PR TITLE
Request Cache logic changes

### LINKED ISSUE #908: --useCache should rely only on the fs
like in older version and not on Redis like in 1.9.

### PR DESCRIPTION
**Pull request by ISNIT0**
Closes #908

### CODE REVIEW

**Comment by kelson42** [comment]
@ISNIT0 Would you please be able to rebase on master?

**Comment by ISNIT0** [comment]
@kelson42 rebased

**Comment by kelson42** [comment]
Retested and exactly same feedback as before: The cache is deleted at the end of the run, it should not. Please also secure that --skipCacheCleaning works fine.

**Comment by ISNIT0** [comment]
Looks like a rebase failed, sorry about that

**Comment by kelson42** [comment]
@ISNIT0 Seems not to be rebased on master

**Comment by kelson42** [comment]
@joe Can you please do something about that?

**Pull request merged**
