### PR TITLE
added polyfill script

### PR DESCRIPTION
**Pull request by MananJethwani**
@kelson42 this solves #1286 
here is a zim file for you to test
[zimfile_with_webp.zip](https://github.com/openzim/mwoffliner/files/5446417/zimfile_with_webp.zip)

### CODE REVIEW

**Comment by kelson42** [comment]
@Jaifroid Does the new proposed ZIM file looks good to you?

**Review by kelson42 — DISMISSED** [review]

**Review by kelson42 — CHANGES_REQUESTED** [review]
All looks good, but there is a problem. If we have a URL like `/A/AC/DC` then the relative path to load js will fail. Not sure for now how to fix that pb.

**Comment by MananJethwani** [comment]
@kelson42 can you give me a proper example in refrence to a zim file or something

**Comment by kelson42** [comment]
http://library.kiwix.org/wikipedia_en_all_maxi/A/AC/DC

**Comment by MananJethwani** [comment]
@kelson42 have a look at this zim file 
[Uploading zimfile_with_webp.zip…]()

**Comment by MananJethwani** [comment]
here is the updated zimfile for test
[zimfile_with_webp.zip](https://github.com/openzim/mwoffliner/files/5451044/zimfile_with_webp.zip)

**Review by kelson42 — APPROVED** [review]

**Pull request merged**
