### PR TITLE
:sparkles: re-write urls with no protocol (#640)

### LINKED ISSUE #640: Prefix URLs without protocol scheme with the one of --mwURL
Wrong external link without scheme (dx.doi.org/%2010.1021/je0497496 in A/1,1,1,2-Tétrafluoroéthane.html)

Reported first in #631

### PR DESCRIPTION
**Pull request by ISNIT0**
Closes #640

### CODE REVIEW

**Comment by kelson42** [comment]
@ISNIT0 We still try to retrieve from `http://upload.wikimedia.org` instead of `https://upload.wikimedia.org/`... looks like the patch does not work everywhere properly.

**Comment by ISNIT0** [comment]
The issue https://github.com/openzim/mwoffliner/issues/640 talks about re-writing anchor hrefs

**Comment by kelson42** [comment]
It's a general problem, this should happen everywhere where it's necessary. Thought the title explains it "Prefix URLs without protocol scheme with the one of --mwURL"!

**Comment by ISNIT0** [comment]
The title is very generic.

Please update the issue

**Comment by kelson42** [comment]
Done

**Pull request merged**
