### PR TITLE
Cleanup AxiosError redundant message.

### PR DESCRIPTION
**Pull request by FledgeXu**
Fix: https://github.com/openzim/mwoffliner/issues/1792

### CODE REVIEW

**Comment by kelson42** [comment]
@FledgeXu Thank you!

**Review by pavel-karatsiuba — CHANGES_REQUESTED** [review]
Please add tests for cases of fully filled err response and if the error object is filled only partially.

**Comment by kelson42** [comment]
I would be OK to only unit test the cleanup function.

**Comment by FledgeXu** [comment]
Ok, I will add it later.

**Comment by FledgeXu** [comment]
I added the unit test case for cleanup function and I also adjust the location of the function.

**Review by pavel-karatsiuba — APPROVED** [review]
LGTM

**Review by pavel-karatsiuba — APPROVED** [review]

**Comment by FledgeXu** [comment]
Thanks for your help!

**Pull request merged**
