### PR TITLE
add zimcheck to e2e tests

### PR DESCRIPTION
**Pull request by ISNIT0**
- [x] Currently causes e2e tests to fail
- [x] Add zimcheck to travis

### CODE REVIEW

**Comment by ISNIT0** [comment]
I've had to revert https://github.com/openzim/mwoffliner/pull/918/commits/dc2033d432352bffaae310a42434369b6b794156

**Comment by ISNIT0** [comment]
@kelson42 This PR is now blocked by needing `zimcheck` 1.0.3 to be released

**Comment by kelson42** [comment]
@ISNIT0 Why?

**Comment by ISNIT0** [comment]
Because tests are failing with 1.0.2 that don't fail with 1.0.3 (specifically because of https://github.com/openzim/zim-tools/issues/44)

**Comment by kelson42** [comment]
@ISNIT0 Thx. Please test with a nightly. We will make a new release next week. If everything OK, we could then modify the download URL and merge that PR.

**Comment by ISNIT0** [comment]
I have tested locally from nightly, this PR is now just waiting for the url to be changed

**Comment by kelson42** [comment]
@mgautierfr Waiting to your feedback here.

**Pull request merged**
