### PR TITLE
#347 Made favicon handling more robust

### PR DESCRIPTION
**Pull request by ISNIT0**

### CODE REVIEW

**Comment by bradyhunsaker** [comment]
The ^^^^ above is supposed to point at the keyword "async".

**Comment by ISNIT0** [comment]
@bradyhunsaker The `async` in this case is not referring to the async package - it's actually new in ES6 ([async/await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function)).

The issue will disappear if you update your NodeJS.
Which version of Node are you using? (`node --version`)

**Comment by ISNIT0** [comment]
@bradyhunsaker Also, could you create an issue so it's clearly documented for other people please? :)

**Comment by bradyhunsaker** [comment]
You are correct.  Some newer node versions work correctly.  I was on 6.14.3 for some reason.  I think that at a hackathon a few months ago the 8. and 10. branches weren't working for some reason.

The package.json file says node >=7.4.0 in the "engines" part.  But that version doesn't work for me.
However, the latest LTS version, 8.12.0, does work for me (as does 10.5.0).
So should we update package.json to reflect that the minimum is 8.12.0 or something?  I'll create an issue for that.

**Pull request merged**
