### PR TITLE
Any reason why details-element-polyfill.js is in the code base #806

### LINKED ISSUE #806: Any reason why details-element-polyfill.js is in the code base
Instead of being a dependence?

### PR DESCRIPTION
**Pull request by Fontirroig**
Fixes #806

### CODE REVIEW

**Comment by kelson42** [comment]
@Fontirroig This is exatly the same PR as I made a few months ago here #903. It will produce invalid ZIM files.

**Comment by Fontirroig** [comment]
@kelson42 it's not the same, I remove the extension ".js" from
'../node_modules/details-element-polyfill/dist/details-element-polyfill.js'

src/util/misc.ts:174 always add the ".js" extension

that causes the following error in `readFilePromise` src/util/misc.ts

`message:"ENOENT: no such file or directory, open '/home/mwoffliner/node_modules/details-element-polyfill/dist/details-element-polyfill.js.js'"
path:"/home/mwoffliner/node_modules/details-element-polyfill/dist/details-element-polyfill.js.js"
stack:"Error: ENOENT: no such file or directory, open '/home/mwoffliner/node_modules/details-element-polyfill/dist/details-element-polyfill.js.js'"
syscall:"open"`

**Comment by Fontirroig** [comment]
I get the following output

`[INFO] Checking zim file wikipedia_bm_articlelist_2019-10.zim
[INFO] Verifying Internal Checksum.. 
  [INFO] Internal checksum found correct
[INFO] Searching for metadata entries..
[INFO] Searching for Favicon..
[INFO] Searching for main page..
[INFO] Verifying Articles' content.. 
[INFO] Searching for redundant articles..
  Verifying Similar Articles for redundancies..
[ERROR] Invalid internal links found :
  A/Manuel_A._Torres (./Manuel_A._Torres) was not found in article A/index
[INFO] Overall Test Status: Fail
[INFO] Total time taken by zimcheck: 0 seconds.`

**Comment by Fontirroig** [comment]
I'll check again and I'll back to you

**Comment by Fontirroig** [comment]
@kelson42 I'm not able to create a ZIM file to test, I get the following output

https://gist.github.com/Fontirroig/6f7d6fb2f67b93a619c470e67a3d70bc

could you give me a hint ?

thank you

**Comment by kelson42** [comment]
@Fontirroig Your are able to get the Zim. The problem is that the content is not correct, I have already given to you, the only hint I can.

**Pull request closed without merging**
