### PR TITLE
Improve category scraping

### PR DESCRIPTION
**Pull request by ISNIT0**
https://framadrop.org/r/dIaIeQVRtO#zZjY9W6s5P6ukctJPxU8GDvEQpzAUPdsqSKXbQohwII=

https://framadrop.org/r/o-_UbqzZrg#qdVLMogZR5NTX6n25to48kvvU9ilRq9dN/WGYYHVvFo=

### CODE REVIEW

**Comment by ISNIT0** [comment]
@kelson42 @Popolechien 
Would love to get some feedback on these ZIMs

**Comment by ISNIT0** [comment]
@kelson42 Without the "simplification"

BM: https://framadrop.org/r/9IKsv2hD0k#A9+y2VUS/MDogxlOccATiomfw/oC6C3RGcnzhpRm+d0=

EN 100: https://framadrop.org/r/fV1uDkOY7l#30fQ8byays/wpiZeguJxKMB0VRvd0gbOGJ++T3xrsYg=

**Comment by kelson42** [comment]
@ISNIT0 "Joliba" on bmwiki homepage should not be a "black link"

**Comment by Popolechien** [comment]
@ISNIT0 Both look fine - if anything I'd rather have the simplified version because it's less heavy, but what's the criteria to decide whether a category is or isn't scraped (I was looking at ``lion`` and we go from 2 to 23 categories)?

**Comment by ISNIT0** [comment]
@kelson42 Fixed redirects and category issues: https://framadrop.org/r/P1S5xi6PRm#A6fiUMsysQsdZzr72yXsT6i/QaYm/Dc97iJZZtYktVg=

**Pull request merged**
