### PR TITLE
:bug: Updated resource referencing

### LINKED ISSUE #613: mwoffliner 1.8 does not rewrite URLS properly
Running `mwoffliner --verbose --mwUrl=https://bm.wikipedia.org/ --adminEmail=kelson@kiwix.org` with both 1.71. and 1.8 give the following result:

With 1.8:
```
# zimdump -f Maninkakan -d out/wikipedia_bm_all_2019-03.zim | grep script
  <script>
  </script>
  <script src="/-/j/js_modules/script.js" class=""></script><script src="/-/j/js_modules/masonry.min.js" class=""></script><script src="/-/j/js_modules/article_list_home.js" class=""></script><script src="/-/j/js_modules/images_loaded.min.js" class=""></script>
  <noscript>
  </noscript>
  <script src="/-/j/js_modules/jsConfigVars.js" class=""></script>
  <script src="/-/j/js_modules/startup.js" class=""></script>
<script src="/-/j/js_modules/jquery.js" class=""></script>
<script src="/-/j/js_modules/mediawiki.js" class=""></script>
<script src="/-/j/js_modules/site.js" class=""></script>
```

With 1.7:
```
# zimdump -f Maninkakan -d out/wikipedia_bm_all_2019-03.zim | grep script
  <script>
  </script>
  <script src="../-/j/js_modules/script.js" class=""></script><script src="../-/j/js_modules/masonry.min.js" class=""></script><script src="../-/j/js_modules/article_list_home.js" class=""></script><script src="../-/j/js_modules/images_loaded.min.js" class=""></script>
  <noscript>
  </noscript>
  <script src="../-/j/js_modules/jsConfigVars.js" class=""></script>
  <script src="../-/j/js_modules/startup.js" class=""></script>
<script src="../-/j/js_modules/jquery.js" class=""></script>
<script src="../-/j/js_modules/mediawiki.js" class=""></script>
<script src="../-/j/js_modules/site.js" class=""></script>
```

Like written in the spec https://wiki.openzim.org/wiki/ZIM_file_format#URLs:

> Absolute URLs, ie. with a leading slash (/) are forbidden, because this avoid including the ZIM contents in any HTTP sub-hierachy. ZIM contents URLs must consequently be relative. Be careful, <article_url> may itself contain slashes (for example "BMW_501/502"). 

This bug is extremely visible in `kiwix-serve` as none of the pictures and CSS and JS is served.

This also seems to be a regression, I don't remember having se that bug 2 weeks ago in 1.8

### PR DESCRIPTION
**Pull request by ISNIT0**
Closes #613

### CODE REVIEW

**Comment by kelson42** [comment]
This can not work like this. What will happen if the title has a "/" in it? All of this was working properly in 1.7, you just need to keep the code.

**Comment by ISNIT0** [comment]
1.7 used `zimwriterfs`, so I can't keep the code - this all has to be re-implemented.

Anyway, `getMediaBase` normalises the title names so that's not a problem

**Comment by kelson42** [comment]
@ISNIT0 What do you mean with normalise? The url for article "AC/DC" should stay "AC/DC" (at the end).

**Comment by ISNIT0** [comment]
@kelson42 You're right, sorry - I mis-understood what you meant

**Comment by ISNIT0** [comment]
Updated this branch, tested and works with Kiwix Mac and kiwix-serve (http://209.250.226.220:8080/test/A/AC/DC)

**Comment by kelson42** [comment]
@ISNIT0 Looks better :)

**Pull request merged**
