### PR TITLE
Update and refactor node-redis

### PR DESCRIPTION
**Pull request by uriesk**
- update redis to current v4
- put the store into an own class
- don't fetch article details from redis again on getArticle, hand them down
- write interfaces for RedisKvs and RedisStore in types.d.ts and stop importing the classes everywhere
- split `RedisKvs.exists` into `.exists` and `.existsMany`
- rewrite the mapping functions of `RedisKvs` to not use `.reduce`
- `--redis` parameter is either redis URL or path to unix socket (v4 changed its constructor, have to now detect by `startsWith('/') || startsWith('./')` if its a path)
- Make sure that stores are flushed on exit, print errors on launch when stores from other runs are found (but continue)
- `getArticleIdsByNS`:
    - batch redis commands together and await them in the next iteration
    - detect when it freezes
    - log time
- `saveArticles`:
    - again batch more redis commands together (getMany for FileDetail and setMany instead of Set)
    - detect when it freezes
    - log time
- `getModuleDependencies`:
    - no silent process.exit(1) on error

Since that one test in the test/jest folder was just about RedisKvs.iterateItem:

- mock-redis is abandoned and no replacement for redisv4 exists, so make our own mock
- move the test to the unit tests and remove it from the github workflow

### CODE REVIEW

**Comment by uriesk** [comment]
painful

**Comment by uriesk** [comment]
I wish you good luck reviewing this.

**Comment by kelson42** [comment]
Small feedback based on a few tests: speed-up mostly visible with ZIM files with pictures: ~10% faster. The others are pretty exactly as fast/quick as before.

**Comment by uriesk** [comment]
just a rebase, no changes

**Comment by kelson42** [comment]
@uriesk  I had a look to the PR and so far I can not see anything chocking me, but this is a very high level review. A question: wouldn't be smart to have a the `redisStore` as singleton?

**Review by kelson42 — APPROVED** [review]

**Comment by kelson42** [comment]
For me locally, the CI does not pass. @pavel-karatsiuba I keep having time to time this scenario since one of the first maintenance PR you have committed:
```
 PASS  test/unit/sanity.test.ts
  Sanity tests
    ✓ Symple sanity test (2 ms)


ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From test/unit/util.test.ts.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From test/unit/util.test.ts.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From test/unit/util.test.ts.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From test/unit/util.test.ts.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From test/unit/util.test.ts.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From test/unit/util.test.ts.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From test/unit/util.test.ts.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From test/unit/util.test.ts.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From test/unit/util.test.ts.


 FAIL  test/unit/util.test.ts
  ● Test suite failed to run

    ReferenceError: Export '__signal_exit_emitter__' is not defined in module

      at node_modules/jest-runtime/build/index.js:1494:16
          at Array.forEach (<anonymous>)

 FAIL  test/unit/urlRewriting.test.ts
  ● Test suite failed to run

    ReferenceError: Export '__signal_exit_emitter__' is not defined in module

      at node_modules/jest-runtime/build/index.js:1494:16
          at Array.forEach (<anonymous>)


ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From test/unit/styles.test.ts.


 FAIL  test/unit/styles.test.ts
  ● Test suite failed to run

    ReferenceError: Export '__signal_exit_emitter__' is not defined in module

      at node_modules/jest-runtime/build/index.js:1494:16
          at Array.forEach (<anonymous>)
```

**Comment by uriesk** [comment]
@kelson42 there are two issues with a singleton... nothing major but something to keep in mind:

1. node-redis v4 wants to connect asynchronously, and as long as it didn't do that, it will throw an error for everything that wants to use it. Not much of an issue if we do that in execute() before anything else happens, but something to keep in mind
2. you can't have two simultaneous instances, which makes the e2e tests weird, where multiple executes() run in parallel. It is interestingly not an issue right now, with the individual RedisKvs stores being singletons, but it turned into an issue when i started working on this PR and didn't have redis in its own class yet.

I don't like those large argument lists either.
I would rather solve those by turning the whole `utils/saveArticles.js` into one class called `Renderer` or something and initialize it with redisStore, downloader, and so on.

**Comment by uriesk** [comment]
@kelson42 @pavel-karatsiuba 
https://github.com/openzim/mwoffliner/pull/1728#issuecomment-1407737202

This is a Timeout issue, when your local machine is a potato compared to the github workflow :)
I get that too sometimes, if you increase the `jest.setTimeout(20000)` at the top of `test/unit/saveArticles.test.js` it goes away.

**Comment by kelson42** [comment]
> @kelson42 @pavel-karatsiuba [#1728 (comment)](https://github.com/openzim/mwoffliner/pull/1728#issuecomment-1407737202)
> 
> This is a Timeout issue, when your local machine is a potato compared to the github workflow :) I get that too sometimes, if you increase the `jest.setTimeout(20000)` at the top of `test/unit/saveArticles.test.js` it goes away.

Sorry for my potato. Indeed it works better by increasing the timeout. Any negative side effect if I put `40000` instead?

**Comment by uriesk** [comment]
no issue

**Comment by pavel-karatsiuba** [comment]
@kelson42 For now this is the one way to fix this issue. You can increase the delay. It only affects test execution time.

**Review by pavel-karatsiuba — APPROVED** [review]
LGTM

**Pull request merged**
