### PR TITLE
Refactoring of Logger module

### PR DESCRIPTION
**Pull request by pavel-karatsiuba**
Use ['info', 'log', 'warn', 'error'] as values for --verbose

fixes: #674

### CODE REVIEW

**Review by kelson42 — CHANGES_REQUESTED** [review]
* the value given should be checked, `--verbose=ddd` just pass. Like any other argument it should be check and if wrong an error should be displayed and mwoffliner should exit.
* In the usage, default value if nothing specified should be documented.
* It should be explain as well that the chosen level print also all the level greather than this. So if you should `warn`, you will get `warn` and `errors`
* Everything should be written to STDOUT except the errors, which should be printed to the STDERR

**Comment by pavel-karatsiuba** [comment]
Added sanitizing for verbose option.
The verbose option can be empty or one of "info", "log", "warn", "error", or "quiet".
An empty value is equal to "info".
The default level is "error".
If --verbose=quiet then don't print messages.

**Review by kelson42 — CHANGES_REQUESTED** [review]
Please rebase and resolve conflicts, have also left a small style feedback

**Review by kelson42 — APPROVED** [review]
LGTM

**Pull request merged**
