### PR TITLE
fixes for custom main page redirects

### PR DESCRIPTION
**Pull request by MananJethwani**
@kelson42 this is a pull request for issue #984 I made an axios get request and checked for redirection this is done in sanitize-arguments as all arguments were to be tested these.

### CODE REVIEW

**Comment by kelson42** [comment]
@MananJethwani Can you please put spaces like in the rest of the code?

**Comment by MananJethwani** [comment]
@kelson42 is it fine now?

**Comment by kelson42** [comment]
@MananJethwani No, after `if` you should have a space.

**Review by kelson42 — COMMENTED** [review]
@MananJethwani This is not the right approach I believe, I think this is superseed by #1260. Please let me know what you think about it.

**Pull request closed without merging**
