### PR TITLE
Add delay between render tests

### PR DESCRIPTION
**Pull request by VadimKovalenkoSNF**
Fixes https://github.com/openzim/mwoffliner/issues/1937

### CODE REVIEW

**Comment by VadimKovalenkoSNF** [comment]
Tests will fail till https://en.wikipedia.org/w/api.php?action=visualeditor&mobileformat=html&format=json&paction=parse&formatversion=2&page=MediaWiki%3ASidebar is unblocked.

**Review by kelson42 — CHANGES_REQUESTED** [review]
Don't put test only related stuff in the software codebase. Create a `test/const.ts`.

I also don't understand why you don't play with the speed factor?

Secure CI is green (should be right?).

**Comment by kelson42** [comment]
I guess the bug is going to be fixed upstream, so should we not close this PR?

**Comment by VadimKovalenkoSNF** [comment]
> I guess the bug is going to be fixed upstream, so should we not close this PR?
@kelson42 , yes, please close it.

**Pull request closed without merging**
