### PR TITLE
Update README.md with more details about npm and deps

### LINKED ISSUE #1261: Error: @openzim/libzim@2.4.2 install
info lifecycle @openzim/libzim@2.4.2~install: Failed to exec install script
Error: @openzim/libzim@2.4.2 install: `npm run download && node-gyp rebuild -v && npm run bundle`
tried installing on node 10, 11 and 12
also tried it on windows and linux
image

### PR DESCRIPTION
**Pull request by MananJethwani**
this resolves #1261

### CODE REVIEW

**Review by kelson42 — CHANGES_REQUESTED** [review]
I have try to test with a Docker instant and I can not get it working:
```
ROM debian:buster

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    make g++ python curl libjpeg-dev autoconf git nodejs npm && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN npm install mwoffliner
```

It fails during the `npm install` (Docker build).

**Comment by MananJethwani** [comment]
let me have a look again if I missed something

**Comment by MananJethwani** [comment]
@kelson42 I tried this 
```
ROM debian:buster

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    make g++ python curl libjpeg-dev autoconf git nodejs npm && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
   npm install -g npm && npm init

RUN npm install mwoffliner
```

**Comment by kelson42** [comment]
Debian Buster `npm` version seems `5.8.0`.

**Comment by kelson42** [comment]
@MananJethwani You Dockerfile fails for me. But that works:
```
FROM debian:buster
USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    make g++ python curl libjpeg-dev automake autoconf git nodejs npm && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN npm install -g npm
RUN apt remove -y --purge npm
RUN whereis npm
RUN npm --version

RUN npm install --unsafe-perm -g mwoffliner
RUN mwoffliner
```

**Pull request merged**
