### PR TITLE
:sparkles: keep mwe-math-mathml-inline HTML (#164)

### LINKED ISSUE #164: Alt text of maths fallback images is missing in wikipedia_en_maths_novid_2017-11.zim
This issue is similar to #114 (mwoffliner should store the alt text of maths fallback images). #114 was closed in September because the latest Wikipedia novid ZIMs were correctly storing the maths alt text.

However, with the file `wikipedia_en_maths_novid_2017-11.zim` this bug has re-appeared. This file only has the SVG images for maths equations, and does not have the alt text which enables MathJax based solutions to display maths equations quickly and with low memory usage. Kiwix-JS-Windows uses a MathJax solution, because extracting SVGs is extremely memory hungry in the JavaScript app (indeed, it crashes the app on lower-memory systems).

Therefore it is very important for mwoffliner to retain the alt-text of maths equations.

### PR DESCRIPTION
**Pull request by ISNIT0**
Closes #164

### CODE REVIEW

**Comment by kelson42** [comment]
@ISNIT0 Could you upload here a test ZIM file for @Jaifroid ? At the end he is the one able to say if he is happy with the fix.

**Comment by Jaifroid** [comment]
I'll be very happy to test, @ISNIT0 & @kelson42!

**Comment by ISNIT0** [comment]
@Jaifroid Great!
Here is a ZIM file with those three articles:
https://framadrop.org/r/Ab5_7w_Hih#Myu7XKLpuLT8NeDVp2sUejUFGE78twruFxYZStER1LU=

**Comment by Jaifroid** [comment]
@ISNIT0 Great! I've checked those articles in the test ZIM and can confirm that the MathML TeX is present in a form I can use. Thank you! 🙂

**Comment by ISNIT0** [comment]
Great! Super happy we're finally able to sort this issue 😄

**Pull request merged**
