### PR TITLE
Fix --verbose argument sanitation

### LINKED ISSUE #1818: Duplicate in cmd line arguments are not checked (was: --verbose does not accept empty value)
```
$ mw --mwUrl="Https://de.wikipedia.org/" --verbose

....

**********

verbose should be empty or one of [info, log, warn, error, quiet].

**********

```

### PR DESCRIPTION
**Pull request by kelson42**
Fixes #1818

### CODE REVIEW

**Comment by kelson42** [comment]
@pavel-karatsiuba Please review and fix (linting)… afaik https://github.com/openzim/mwoffliner/pull/1785 was not working at all. You confirm or I miss something?

**Comment by pavel-karatsiuba** [comment]
@kelson42 I have created the branch to print the "verbose" parameter value into the log. Can you please test your command with this branch: https://github.com/openzim/mwoffliner/pull/1820

I created the branch because I can't reproduce this bug. If I execute the command with --verbose in the source code it is equal to true.

**Comment by kelson42** [comment]
@pavel-karatsiuba OK.... I will.

**Comment by kelson42** [comment]
Your PR does not really clearly help IMO.

I have just added a debug log to dump the `argv` (see last commit). Here is what I get:
```
$ mw --mwUrl="https://bm.wikipedia.org" --verbose

> mwoffliner@1.12.1 start
> ./node_modules/.bin/ts-node-esm ./src/cli.ts --adminEmail=kelson@kiwix.org --osTmpDir=/dev/shm --verbose --optimisationCacheUrl=http://s3.us-west-1.wasabisys.com/?bucketName=org-kiwix-dev-mwoffliner&keyId=6JE56A5IWY5Z3H3L3KH6&secretAccessKey=m2vQMjnneDjnrYztjfHrAUKneIf0SNGt75k9iITm --mwUrl=https://bm.wikipedia.org --verbose

arguments: {
  _: [ [length]: 0 ],
  adminEmail: 'kelson@kiwix.org',
  'admin-email': 'kelson@kiwix.org',
  osTmpDir: '/dev/shm',
  'os-tmp-dir': '/dev/shm',
  verbose: [ true, true, [length]: 2 ],
  optimisationCacheUrl: 'http://s3.us-west-1.wasabisys.com/?bucketName=org-kiwix-dev-mwoffliner&keyId=6JE56A5IWY5Z3H3L3KH6&secretAccessKey=m2vQMjnneDjnrYztjfHrAUKneIf0SNGt75k9iITm',
  'optimisation-cache-url': 'http://s3.us-west-1.wasabisys.com/?bucketName=org-kiwix-dev-mwoffliner&keyId=6JE56A5IWY5Z3H3L3KH6&secretAccessKey=m2vQMjnneDjnrYztjfHrAUKneIf0SNGt75k9iITm',
  mwUrl: 'https://bm.wikipedia.org',
  'mw-url': 'https://bm.wikipedia.org',
  '$0': 'node_modules/ts-node/dist/child/child-entrypoint.js'
}
[log] [2023-03-30T10:45:37.725Z] Starting mwoffliner v1.12.1...
```

and

```
$ mw --mwUrl="https://bm.wikipedia.org" --verbose=foobar

> mwoffliner@1.12.1 start
> ./node_modules/.bin/ts-node-esm ./src/cli.ts --adminEmail=kelson@kiwix.org --osTmpDir=/dev/shm --verbose --optimisationCacheUrl=http://s3.us-west-1.wasabisys.com/?bucketName=org-kiwix-dev-mwoffliner&keyId=6JE56A5IWY5Z3H3L3KH6&secretAccessKey=m2vQMjnneDjnrYztjfHrAUKneIf0SNGt75k9iITm --mwUrl=https://bm.wikipedia.org --verbose=foobar

arguments: {
  _: [ [length]: 0 ],
  adminEmail: 'kelson@kiwix.org',
  'admin-email': 'kelson@kiwix.org',
  osTmpDir: '/dev/shm',
  'os-tmp-dir': '/dev/shm',
  verbose: [ true, 'foobar', [length]: 2 ],
  optimisationCacheUrl: 'http://s3.us-west-1.wasabisys.com/?bucketName=org-kiwix-dev-mwoffliner&keyId=6JE56A5IWY5Z3H3L3KH6&secretAccessKey=m2vQMjnneDjnrYztjfHrAUKneIf0SNGt75k9iITm',
  'optimisation-cache-url': 'http://s3.us-west-1.wasabisys.com/?bucketName=org-kiwix-dev-mwoffliner&keyId=6JE56A5IWY5Z3H3L3KH6&secretAccessKey=m2vQMjnneDjnrYztjfHrAUKneIf0SNGt75k9iITm',
  mwUrl: 'https://bm.wikipedia.org',
  'mw-url': 'https://bm.wikipedia.org',
  '$0': 'node_modules/ts-node/dist/child/child-entrypoint.js'
}
[error] [2023-03-30T10:49:58.215Z] Failed to run mwoffliner after [0s]: {
	"stack": "Error: verbose should be empty or one of [info, log, warn, error, quiet].\n    at sanitize_verbose (file:///home/kelson/code/mwoffliner/src/sanitize-argument.ts:93:11)\n    at sanitize_all (file:///home/kelson/code/mwoffliner/src/sanitize-argument.ts:25:3)\n    at file:///home/kelson/code/mwoffliner/src/cli.ts:59:1\n    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)",
	"message": "verbose should be empty or one of [info, log, warn, error, quiet]."
}
[error] [2023-03-30T10:49:58.215Z] 

**********

verbose should be empty or one of [info, log, warn, error, quiet].

**********
```

@pavel-karatsiuba Do you get other values for `argv`? If "no", you confirm it works fine now?

**Comment by pavel-karatsiuba** [comment]
@kelson42 
You should edit your `mw` command. When you execute `$ mw --mwUrl="https://bm.wikipedia.org" --verbose` you are executing `./node_modules/.bin/ts-node-esm ./src/cli.ts --adminEmail=kelson@kiwix.org --osTmpDir=/dev/shm --verbose ...  --mwUrl=https://bm.wikipedia.org --verbose=foobar`.

So `mw` already contains `--verbose` and you write the parameter twice.
Also, edit your previous comment because it contains sensual information "secretAccessKey".

**Comment by kelson42** [comment]
* How should `mw` look like?
* What is the purpose of `./src/cli.ts` then?
* Why the `README` given command `npm run mwoffliner -- --help` does not work for me?

**Comment by kelson42** [comment]
@pavel-karatsiuba I'm still expecting an answer here.

**Comment by pavel-karatsiuba** [comment]
- Actually, you don't need to edit `mw` command. Because after I fix this issue, your command should work or you will see an error with a clear message.
- `./src/cli.ts` is the script entry point.
- Maybe `npm run mwoffliner -- --help` is not working because you did not execute `npm i`. Or it should give you the error message

**Comment by kelson42** [comment]
Inappropriate PR as the root of the problem is not a problem in the parsing of the `--verbose` argument but that I have overseen the duplicated `--verbose` (fixed with #1823).

**Pull request closed without merging**
