### PR TITLE
Re-written README

### PR DESCRIPTION
**Pull request by ISNIT0**
I may have missed some-bits out.
Thoughts?

### CODE REVIEW

**Comment by ISNIT0** [comment]
Could you take a look at this please @kelson42

**Comment by kelson42** [comment]
@ISNIT0 Yes, I will.

**Comment by ISNIT0** [comment]
@kelson42 Any thoughts?

**Comment by ISNIT0** [comment]
@kelson42 This is currently blocking https://github.com/openzim/mwoffliner/issues/423
Could you take a look please?

**Pull request merged**
