### PR TITLE
issue/1176/redis-iterate

### LINKED ISSUE #1176: Remarks about RedisKVS.iterateItems()
Looking around in MWoffliner code I came to `RedisKvs.iterateItems()` (and `RedisKvs..iterateItems()`). https://github.com/openzim/mwoffliner/blob/master/src/util/RedisKvs.ts#L165

If I understand properly this function is at the core of the iteration over all articles/images/, has a `while (true)` loop.... but not log entry at all! Sounds a good candidate to me about where it could fail.

So here a few remarks/proposals:
* it should be a `do... while()` test, not a `while`.
* `depleted` is useless, we should just return/exit (if necessary, should not).
* `RedisKvs.scan()` `reject(err)` seems not handled at all!
* I don't really get it between `RedisKvs.scan()` and `pendingScan: Promise<ScanResult>`. To me they should be merged in one method and the only thing shared should be the `scanCursor`.
* This line `const items = Array.from(data, (x, k) => k % 2 ? undefined : [x, data[k + 1]]).filter((x) => x);` is a mystery to me and I wonder what it does.
* We should not `break` IMO, the `while` loop should be exited properly with its checks if necessary.
* The line `scanCursor = cursor` create the conditions of a problem by lately resetting the scanCursor which might have been changed meanwhile by an other async method.
* There is no security considering that the same element of Redis can be returned many times.
@midik Maybe you have more to say/change to this. I have the strong feeling that this iterator is not done properly.

### PR DESCRIPTION
**Pull request by midik**
Fix #1176

### CODE REVIEW

**Comment by midik** [comment]
not sure why codecov doesn't count jest coverage (`Dowloader.ts / getJsonCb()` for example)

**Comment by midik** [comment]
> At least 20% slower with bm.wikipedia.org (with S3 cache)

@kelson42 Just got some benchmarks for bm.wiki.

Running with:
```
/home/mid/.nvm/versions/node/v12.9.0/bin/node -r ts-node/register /home/mid/_projects/kiwix/mwoffliner/src/cli.ts --adminEmail=admin@kiwix.org --mwUrl=http://bm.wikipedia.org/ --format=nopic:nopic
```
On localhost:
```
 mid@mid-arch  ~  screenfetch -n
 OS: Arch Linux 
 Kernel: x86_64 Linux 5.8.3-zen1-1-zen
 Uptime: 2h 38m
 Packages: 1897
 Shell: fish 3.1.2
 Resolution: 4480x1440
 DE: KDE 5.73.0 / Plasma 5.19.4
 WM: KWin
 GTK Theme: Adwaita-dark [GTK2/3]
 Icon Theme: OieIcons
 Disk: 400G / 464G (87%)
 CPU: Intel Core i7-6600U @ 4x 3.4GHz [57.0°C]
 GPU: Mesa Intel(R) HD Graphics 520 (SKL GT2)
 RAM: 9142MiB / 15739MiB
```
Connection:
```
 mid@mid-arch  ~  speedtest-cli
Retrieving speedtest.net configuration...
Testing from Sprint Inet LLC (91.204.228.103)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Sprint-Inet (Novorossiysk) [6.95 km]: 9.603 ms
Testing download speed................................................................................
Download: 21.18 Mbit/s
Testing upload speed......................................................................................................
Upload: 14.00 Mbit/s
```

**Results**:

Run on `issue/1176/redis-iterate` branch:
64s - [1-new.log](https://github.com/openzim/mwoffliner/files/5128546/1-new.log)
55s - [2-new.log](https://github.com/openzim/mwoffliner/files/5128547/2-new.log)
56s - [3-new.log](https://github.com/openzim/mwoffliner/files/5128550/3-new.log)

Run on `master` branch (bfd2f36131e3091c84ae7e7e732033b1d80d3210):
92s - [4-master.log](https://github.com/openzim/mwoffliner/files/5128551/4-master.log)
86s - [5-master.log](https://github.com/openzim/mwoffliner/files/5128552/5-master.log)
88s - [6-master.log](https://github.com/openzim/mwoffliner/files/5128553/6-master.log)

**Comment by midik** [comment]
> Get stuck with mi.wikipedia.org around 50% of the time (with S3 cache)

Run on `master` branch (bfd2f36):
767s - [mi-1-master.log](https://github.com/openzim/mwoffliner/files/5133086/mi-1-master.log)
711s - [mi-2-master.log](https://github.com/openzim/mwoffliner/files/5133087/mi-2-master.log)
703s - [mi-3-master.log](https://github.com/openzim/mwoffliner/files/5133089/mi-3-master.log)

Run on `issue/1176/redis-iterate` branch:
214s - [mi-4-new.log](https://github.com/openzim/mwoffliner/files/5133091/mi-4-new.log)
221s - [mi-5-new.log](https://github.com/openzim/mwoffliner/files/5133092/mi-5-new.log)
245s - [mi-6-new.log](https://github.com/openzim/mwoffliner/files/5133093/mi-6-new.log)

¯\\\_(ツ)\_/¯

**Comment by kelson42** [comment]
My own runs with:

 `./src/cli.ts --adminEmail=admin@kiwix.org --mwUrl=http://bm.wikipedia.org/ --format=nopic:nopic`:

master:
* 47.325s
* 1m4.391s
* 50.554s

redis-iterate:
* 44.251s
* 0m46.337s
* 0m47.084s

 `./src/cli.ts --adminEmail=admin@kiwix.org --mwUrl=http://mi.wikipedia.org/ --format=nopic:nopic`:

master:
* 7m16.326s
*
*

redis-iterate:
* Stuck
*
*

:(

**Comment by midik** [comment]
> My own runs with:

Wondering why your timers looks different than mine... anyways we cannot consider `redis-iterate` 20% slower than `master` (or even slower at all) :)
Most interesting thing is why `mi` tends to stuck. I gonna make more runs today and also will run something bigger.

**Comment by kelson42** [comment]
@midik I confirm that today - for a reason I can not explain - the runs without any pictures are successfuly and quick(er) with redis-iterate. We should test as well with pictures/S3.... but the blocker is clearly the fact that it get stuck for me.

**Comment by ShadowJonathan** [comment]
@kelson42 any movement on this?

**Comment by kelson42** [comment]
@ShadowJonathan Last time I verified this PR it was not working fine (process was stuck if I remember properly) and this PR is orphaned, aiming for a new dev. To finish the work.

**Comment by kelson42** [comment]
Superseeded by #1714

**Pull request closed without merging**
