### PR TITLE
remove unnecessary async wrapper + refactoring

### LINKED ISSUE #1081: Getting OOM while iterating custom article list
Exterrior:
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8fa090 node::Abort() [node]
 2: 0x8fa0dc  [node]
 3: 0xb0052e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb00764 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xef4c72  [node]
 6: 0xef4d78 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [node]
 7: 0xf00e52 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
```
Command:
```
node ./lib/cli.js --adminEmail=contact@kiwix.org --format=nopic:nopic --mwUrl=https://no.wikipedia.org/ --customZimFavicon=https://no.wikipedia.org/static/images/project-logos/nowiki.png --customZimTitle=Wikipedia --customZimDescription="offline versjon av Wikipedia på norsk bokmål (Norge)" --verbose --outputDirectory=./output --articleList="_misc/tsv/no-all.tsv" > _misc/log/no2.log
```
...where `_misc/tsv/no-all.tsv` is unpacked tsv from there http://download.openzim.org/wp1/nowiki_2020-04/all.tsv.zip

Env: `GCP e2-highcpu-8 (8 vCPUs, 8 GB memory) / northamerica-northeast1-a`
```
 OS: Debian 9.12 stretch
 Kernel: x86_64 Linux 4.9.0-12-amd64
 Uptime: 59m
 Packages: 416
 Shell: fish
 CPU: Intel Xeon CPU @ 2GHz
 RAM: 756MiB / 7987MiB
```
Initial vector: `mwoffliner.lib.ts` starting from line 412

### PR DESCRIPTION
**Pull request by midik**
Fixes #1081

Fix OOM + refactoring

Tested with same conditions on GCP.

### CODE REVIEW

**Comment by kelson42** [comment]
@bakshiutkarsha I have rebase on `master. Could you please review that PR?

**Comment by bakshiutkarsha** [comment]
@midik The `--customFlavour` test failed for me with this error:

```
 Fatal error in , line 0
# Check failed: result.second.
#
#
#
#FailureMessage Object: 0x7ffc38d7cea0
 1: 0xa95a01  [node]
 2: 0x19617d4 V8_Fatal(char const*, ...) [node]
 3: 0xe58149 v8::internal::GlobalBackingStoreRegistry::Register(std::shared_ptr<v8::internal::BackingStore>) [node]
 4: 0xbc5418 v8::ArrayBuffer::GetBackingStore() [node]
 5: 0xa08589 node::Buffer::New(node::Environment*, char*, unsigned long, void (*)(char*, void*), void*) [node]
 6: 0xa089f3 node::Buffer::New(v8::Isolate*, char*, unsigned long, void (*)(char*, void*), void*) [node]
 7: 0x9fdbdd napi_create_external_buffer [node]
 8: 0x7f5cd9369524 Article::getData(Napi::CallbackInfo const&) [/home/utkarsha_bakshi/mwoffliner/node_modules/@openzim/libzim/build/Release/zim_binding.node]
 9: 0x7f5cd937263c Napi::ObjectWrap<Article>::InstanceGetterCallbackWrapper(napi_env__*, napi_callback_info__*) [/home/utkarsha_bakshi/mwoffliner/node_modules/@openzim/libzim/build/Release/zim_binding.node]
10: 0x9e2f0f  [node]
11: 0x133f44d  [node]


Illegal instruction (core dumped)
```

**Comment by kelson42** [comment]
@bakshiutkarsha What is your exact command line to reproduce that crash?

**Comment by bakshiutkarsha** [comment]
> @bakshiutkarsha What is your exact command line to reproduce that crash?

I simply just ran `npm run test`

**Comment by kelson42** [comment]
@bakshiutkarsha I have rebased and tested. Tests run fine for the CI and for me. I guess this is something specific to your setup. What is your version of nodejs?

**Comment by bakshiutkarsha** [comment]
> @bakshiutkarsha I have rebased and tested. Tests run fine for the CI and for me. I guess this is something specific to your setup. What is your version of nodejs?

My node version is v14.2.0, and yes after rebasing master it worked for me too.

**Pull request merged**
