### PR TITLE
Fixes for edutech + refactoring

### LINKED ISSUE #1059: Footer links are not always OK
See the bad link https://edutechwiki.unige.ch/fmediawiki/index.phpInstrumentation?oldid=5758 in http://library.kiwix.org/edutechwiki_fr_all_maxi_2020-03/A/Instrumentation for example.

### PR DESCRIPTION
**Pull request by midik**
@kelson42 Once we merge this, could you please change `mwWikiPath` flag for `edutech` recipes to be:
```
--mwWikiPath=./
```
(I have no permissions for that).
This bug would impact other sources that have `mwWikiPath: index.php` (we have 23 total), so we need to change them accordingly.

@bakshiutkarsha in this branch based on the changes made in PR #1089, please don't be confused by many commits here (actually, here are only 3 commits). Once you approved #1089, I'll rebase this one and number of commits here will be reduced ;)

Fixes #1059

### CODE REVIEW

**Comment by midik** [comment]
[edutechwiki_fr_all_nopic_2020-04.zim.gz](https://github.com/openzim/mwoffliner/files/4550975/edutechwiki_fr_all_nopic_2020-04.zim.gz)

**Comment by kelson42** [comment]
> This bug would impact other sources that have `mwWikiPath: index.php` (we have 23 total), so we need to change them accordingly.

Hmmm `./` is a really strange path. Why `index.php` does not work anymore. What is the nature of things you have changed here?

**Comment by kelson42** [comment]
@midik I think there is two problems with the ZIM you have posted:
* The title is not really like in other wikis, it seems a `<hr>` link is missing
* AFAIK there is never a title on the welcome page.

**Comment by midik** [comment]
> Hmmm `./` is a really strange path. Why `index.php` does not work anymore. What is the nature of things you have changed here?

@kelson42 
It's just a way to exclude it from the path chain. No-op. Default value is `wiki/` so that we can't just omit it.
Edutech has really strange [path config](http://edutechwiki.unige.ch/fr/Sp%C3%A9cial:Version) on their side. So, strictly speaking, rather than having this (current config):
```
--mwUrl=https://edutechwiki.unige.ch/fmediawiki/
--mwApiPath=api.php
--mwModulePath=load.php
--mwWikiPath=index.php
```
... we should have this:
```
--mwUrl=https://edutechwiki.unige.ch/fr
--mwApiPath=../fmediawiki/api.php
--mwWikiPath=../fmediawiki/index.php
--mwModulePath=../fmediawiki/load.php

```
...where `../` started to work since I got rid string concatenation there.
Anyways, both of these configs lead us to this particular issue with bad links in the footer. The reason is that `mwWikiPath` is being used as a base for constructing the links in the footer template (through `Mediawiki.webUrl`). That makes sense for me: I consider `webUrl` as the website root. However, according the [specs](https://www.mediawiki.org/wiki/Manual:Index.php), `index.php` couldn't considered as the path for constructing the links. In other templates, we use `Mediawiki.base` (which is wrong as by me). So we could use `Mediawiki.base` in the footer too, but I consider that as workaround. That's why I didn't touch template and keep `webUrl` there. So, according the second schema, it would be
```
--mwWikiPath=../fmediawiki
```
.. which doesn't seem "weird" anymore.

The nature of other things here is just a by-the-way refactoring of the things that sometimes, doesn't deserve for another PR.

**Comment by midik** [comment]
> * The title is not really like in other wikis, it seems a `<hr>` link is missing
> * AFAIK there is never a title on the welcome page.

I think that's because I didn't provide custom main page and custom title while testing. The command that I used to generate that zim above is exactly:
```
node -r ts-node/register src/cli.ts
  --format=nopic:nopic
  --adminEmail=admin@kiwix.org
  --mwUrl=https://edutechwiki.unige.ch/fr
  --mwApiPath=../fmediawiki/api.php
  --mwWikiPath=./
  --mwModulePath=../fmediawiki/load.php
  --useDownloadCache
  --downloadCacheDirectory=cache
  --speed=0.1
```

**Comment by kelson42** [comment]
@midik No, there should not be a title here, see for example http://library.kiwix.org/wikipedia_cs_all_maxi (with default main page).

**Comment by kelson42** [comment]
> --mwUrl=https://edutechwiki.unige.ch/fmediawiki/
> --mwApiPath=api.php
> --mwModulePath=load.php
> --mwWikiPath=index.php

@midik This is the simpliest and proper config IMO. Why this is not correct?

**Comment by midik** [comment]
@kelson42 fixed

**Comment by kelson42** [comment]
@midik I will test it, but can you please secure that codecoverage does not decrease and the Codefactor is green?

**Comment by kelson42** [comment]
@midik Does not work for me (many errors and then I have stopeed it):
```
$ mwoffliner --adminEmail="contact@kiwix.org" --customMainPage="Zim" --customZimDescription="Le wiki des technologies éducatives" --format="novid:maxi" --mwUrl="https://edutechwiki.unige.ch/fr" --osTmpDir="/dev/shm" --speed="0.1" --verbose --mwApiPath="../fmediawiki/api.php" --mwWikiPath="./" --mwModulePath="../fmediawiki/load.php"
[log] [2020-04-30T16:33:19.199Z] Getting text direction...
[log] [2020-04-30T16:33:19.200Z] Getting site info...
[log] [2020-04-30T16:33:19.201Z] Getting sub-title...
[info] [2020-04-30T16:33:19.202Z] Downloading [https://edutechwiki.unige.ch/fr/./]
[info] [2020-04-30T16:33:19.203Z] Getting JSON from [https://edutechwiki.unige.ch/fr/../fmediawiki/api.php?action=query&meta=siteinfo&format=json&siprop=general|namespaces|statistics|variables|category|wikidesc]
[info] [2020-04-30T16:33:19.203Z] Downloading [https://edutechwiki.unige.ch/fr/./]
[log] [2020-04-30T16:33:19.316Z] Not able to download content for https://edutechwiki.unige.ch/fr/./ due to Error: Request failed with status code 400
[log] [2020-04-30T16:33:19.320Z] Not able to download content for https://edutechwiki.unige.ch/fr/./ due to Error: Request failed with status code 400
[info] [2020-04-30T16:33:19.417Z] Downloading [https://edutechwiki.unige.ch/fr/./]
[info] [2020-04-30T16:33:19.420Z] Downloading [https://edutechwiki.unige.ch/fr/./]
[log] [2020-04-30T16:33:19.502Z] Not able to download content for https://edutechwiki.unige.ch/fr/./ due to Error: Request failed with status code 400
[log] [2020-04-30T16:33:19.511Z] Not able to download content for https://edutechwiki.unige.ch/fr/./ due to Error: Request failed with status code 400
[info] [2020-04-30T16:33:19.702Z] Downloading [https://edutechwiki.unige.ch/fr/./]
[info] [2020-04-30T16:33:19.712Z] Downloading [https://edutechwiki.unige.ch/fr/./]
[log] [2020-04-30T16:33:19.799Z] Not able to download content for https://edutechwiki.unige.ch/fr/./ due to Error: Request failed with status code 400
[log] [2020-04-30T16:33:19.803Z] Not able to download content for https://edutechwiki.unige.ch/fr/./ due to Error: Request failed with status code 400
```

**Comment by kelson42** [comment]
@midik Forget my last comment, I don't have tested the proper version of MWoffliner. Sorry about that.

**Comment by kelson42** [comment]
@midik Running a test but I really get a lot of warnings like this:
```
[warn] [2020-05-01T06:52:32.378Z] Failed to get article [Le_raton_conteur] using remote Parsoid, trying with local one TypeError: Cannot read property 'displaytitle' of undefined
    at renderMCSArticle (/home/kelson/code/mwoffliner/src/util/articleRenderers.ts:107:39)
    at /home/kelson/code/mwoffliner/src/util/articleRenderers.ts:57:26
    at Generator.next (<anonymous>)
    at fulfilled (/home/kelson/code/mwoffliner/src/util/articleRenderers.ts:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Is that normal? What is going on here exactly?

**Comment by midik** [comment]
@kelson42 fixed the warnings and related misbehavior

**Pull request merged**
