### PR TITLE
:whale: fixing docker build to use committed code

### LINKED ISSUE #722: Build mwoffliner from source in Docker
To avoid sync problem with npmjs.org

### PR DESCRIPTION
**Pull request by ISNIT0**
Closes #722

### CODE REVIEW

**Comment by kelson42** [comment]
@ISNIT0 Why no CI report here?

**Comment by kelson42** [comment]
This seems to fail for me:
```
$ docker build docker/ -t test
Sending build context to Docker daemon  5.632kB
Step 1/13 : FROM node:10
 ---> 90fa0611d45b
Step 2/13 : RUN apt update && apt install -y --no-install-recommends make g++ curl git
 ---> Using cache
 ---> eaa1975ed541
Step 3/13 : RUN apt install -y --no-install-recommends imagemagick
 ---> Using cache
 ---> b630fea25d78
Step 4/13 : RUN npm --global config set user root
 ---> Using cache
 ---> 381d74b826e2
Step 5/13 : WORKDIR /mwoffliner
 ---> Using cache
 ---> 592e3fce4edf
Step 6/13 : COPY package*.json ./
COPY failed: no source files were specified
```

**Comment by ISNIT0** [comment]
@kelson42 Can we have a look at the dockerhub configuration please? Looks like the build context is wrong.

**Comment by ISNIT0** [comment]
The CI is running, click "Show all checks"

**Comment by kelson42** [comment]
@ISNIT0 What is the local command to build the image?

**Comment by ISNIT0** [comment]
From that directory: `docker build . -f docker/Dockerfile`

**Comment by kelson42** [comment]
This does not work for me and the Dockerfile is broken, but I will have a look.

**Comment by kelson42** [comment]
@ISNIT0 I have fixed the `Dockerfile`. I believe the hub.docker.com is properly configured, but we will have to see that when we are so far.

**Comment by ISNIT0** [comment]
@kelson42 
It seems you've replaced `COPY . .` with lots of individual copies... This is not idea. Please just use the `.dockerignore` file that I've already created.

**Comment by kelson42** [comment]
@ISNIT0 I prefer to be explicit here. Relying only on the `.dockerignore` is implicit copying which leads to the following situation:
* Difficult to immediately know what is copied or not to the image
* Does not secure that you never publish here something which is not intended
* No way to forget to maintain the COPY instructions (which might be perfectly the case with the .dockerignore)
* Not more work to maintain the COPY instructions in the Dockerfile than to maintain the `.dockerignore`

That said:
* I might COPY too much?
* Not against keeping the `.dockerignore` like it is.

**Comment by ISNIT0** [comment]
Using `.dockerignore` is explicitly listed under Docker best practices.
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#exclude-with-dockerignore

If you want to keep the multiple `COPY`s, it's best to remove the `.dockerignore` as it's confusing.

Please merge when you're happy with it.

**Comment by kelson42** [comment]
I want to keep the `.dockerignore` like you made it. This is a security.

**Pull request merged**
