### PR TITLE
TypeScript conversion

### PR DESCRIPTION
**Pull request by ISNIT0**
NOTE: This PR is not into `master`, but into `ISNIT0/ts-convert`
This goes hand-in-hand with #402

This PR:
- Renames JS files to TS
- Fixes all TSLint issues
- Leaves `./bin/*.js` files as JS
- Moves more resources into the `res/` dir

Please look at each commit separately

### CODE REVIEW

**Comment by ISNIT0** [comment]
@bradyhunsaker Thoughts?

**Comment by ISNIT0** [comment]
@bradyhunsaker @kelson42 I'm going to go ahead and assume "no news is good news" and merge these PRs in this afternoon unless I hear otherwise 👍

**Comment by bradyhunsaker** [comment]
Hi Joe,

I apologize for missing this and other direct requests to me.  I missed
them among the other generic issue updates (that weren't specifically to
me).  I didn't have or make time to work on mwoffliner in the past two
months, so I wasn't reading the emails.  But I would have replied to these
direct requests if I had seen them.  I will start checking the emails more
carefully, even when I don't have time to make many contributions.  And I
think Gmail may have called them out as important, so I don't really have a
good excuse.

I now plan to spend a little time on mwoffliner.

This commit makes it look like you made a TypeScript conversion, but the
changes don't include indicating types, for example.
Is it correct that you switched to TypeScript?  If so, shouldn't we put
some guidance in README and CONTRIBUTING?  Or maybe this is preparatory
formatting changes but it's not actually TypeScript yet?

**Comment by ISNIT0** [comment]
Hi @bradyhunsaker 
As per the issue: https://github.com/openzim/mwoffliner/issues/386

This pull request completed step 1 in "Proposed Plan".
The files in src are all `.ts` files and there are a few type indicators. The plan is to slowly make the TypeScript compiler stricter to improve the type coverage. You're right, it would be good to add something to the README/CONTRIBUTING files.

👍

**Pull request merged**
