### PR TITLE
Fix a few geo tests in the CI

### PR DESCRIPTION
**Pull request by kelson42**
Values have changed upstream

### CODE REVIEW

**Review by audiodude — CHANGES_REQUESTED** [review]
CI still failing...

**Comment by kelson42** [comment]
@audiodude Yes, this is because we have lost WP1 selection files, see https://github.com/openzim/wp1/issues/171#issuecomment-2515397584. I propose to fix this by creating an arbitrary selection in WP1 to fix the CI for the time beeing.

**Comment by audiodude** [comment]
> @audiodude Yes, this is because we have lost WP1 selection files, see [openzim/wp1#171 (comment)](https://github.com/openzim/wp1/issues/171#issuecomment-2515397584). I propose to fix this by creating an arbitrary selection in WP1 to fix the CI for the time beeing.

Is that really the issue? Looking at the failed test run () I see this:

```
FAIL test/e2e/en10.e2e.test.ts
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:133:18)
      at node_modules/@jest/core/build/TestScheduler.js:254:19
      at node_modules/emittery/index.js:363:13
          at Array.map (<anonymous>)
      at Emittery.emit (node_modules/emittery/index.js:361:23)
```

Though I don't understand how that wasn't a problem in the past.

**Comment by audiodude** [comment]
Oh I see it now:

```
  console.error
    [error] [2024-12-04T03:32:25.313Z] Failed to read articleList from URL: https://download.openzim.org/wp1/enwiki/tops/10.tsv
```

The message is incorrect, because the tests only get **defined** after the `testAllRenders` method executes. Also it's hard to read the CI output because of #2038

**Review by audiodude — APPROVED** [review]

**Pull request merged**
