### PR TITLE
Remove useless encodeURI()

### PR DESCRIPTION
**Pull request by kelson42**

### CODE REVIEW

**Comment by midik** [comment]
something wrong with the tests, checking...

**Comment by kelson42** [comment]
> something wrong with the tests, checking...

Thank you, I don't understand why the automated tests fail here!

**Comment by midik** [comment]
in short: encodeURI is required here because we need to encode `|` symbols.
changed vs original:
```
 Article html processing

    [log] [2020-04-28T10:55:03.114Z] Getting text direction...
    [log] [2020-04-28T10:55:03.117Z] Getting site info...
    [log] [2020-04-28T10:55:03.119Z] Getting sub-title...
    [log] [2020-04-28T10:55:04.156Z] Text direction is [ltr]
    https://en.wikipedia.org/w/api.php?action=parse&format=json&page=London&prop=modules|jsconfigvars|headhtml}
    https://en.wikipedia.org/w/api.php?action=parse&format=json&page=London&prop=modules%7Cjsconfigvars%7Cheadhtml
    [log] [2020-04-28T10:55:19.791Z] Done with downloading a total of [1] articles

    ✖ TypeError: Cannot read property 'bufferData' of undefined
    ------------------------------------------------------------

**Comment by kelson42** [comment]
I want to give a new attempt.

**Pull request merged**
