### PR TITLE
Packages updated. Configs changed to use ESM

### LINKED ISSUE #1667: Update all dependences to latest version
and that way we have no (fixable) security issues still open.

### LINKED ISSUE #1688: Migrate to ESM format
The mwoffliner package is currently based on CommonJS (CJS) format and it is good time to migrate to newer ES module (ESM) format.

### LINKED ISSUE #1732: Error? by running tests
Running the test gives a strange error... but the overall test is OK.
```
 RUNS  test/e2e/en10.e2e.test.ts
T:19; A:564; RA:484; CA:70; UA:10; FA:0; IA:10; C:2; CC:2; UC:0; WC:0
T:20; Waiting for workers
T:20; ResolveRedirectIndexes
Resolve redirect
T:20; Set article indexes
set index
T:20; Resolve mimetype
T:20; create title index
T:20; 566 title index created
T:20; 4 clusters created
T:20; write zimfile :
T:20;  write mimetype list
T:20;  write directory entries
T:20;  write url prt list
T:20;  write title index
T:20;  write cluster offset list
T:20;  write header
T:20;  write checksum
 FAIL  test/e2e/en10.e2e.test.ts (134.365 s)
  en10
    ✕ Simple articleList (120586 ms)

  ● en10 › Simple articleList

    thrown: "Exceeded timeout of 120000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      25 |   };
      26 |
    > 27 |   test('Simple articleList', async () => {
         |   ^
      28 |     await execa(`redis-cli flushall`, { shell: true });
      29 |
      30 |     const outFiles = await mwoffliner.execute(parameters);

      at test/e2e/en10.e2e.test.ts:27:3
      at test/e2e/en10.e2e.test.ts:10:1
```

What is going on?

### PR DESCRIPTION
**Pull request by pavel-karatsiuba**
Fixes #1688
Fixes #1667 
Fixes #1732

### CODE REVIEW

**Review by kelson42 — CHANGES_REQUESTED** [review]
`CONTRIBUTING.md` should be updated. `./node_modules/.bin/ts-node ./src/cli.ts --mwUrl=https://bm.wikipedia.org ` does not work anymore

**Comment by pavel-karatsiuba** [comment]
> * Not clear what `test:pattern-coverage` and `test:pattern` mean?

`test:pattern` uses to execute tests by some template. For example all tests which are ends on 's3.test.ts': `test:pattern s3.test.ts`

**Comment by kelson42** [comment]
@pavel-karatsiuba So it accepts a regex?

**Comment by pavel-karatsiuba** [comment]
@kelson42 Yes, it is possible to run test suites by providing a regex.

**Comment by kelson42** [comment]
@pavel-karatsiuba Woukd be helpful then to see tgis in the example you have given.

**Pull request merged**
