### PR TITLE
AWS SDK jsv3 migration

### LINKED ISSUE #1840: Upgrade aws-sdk version
We get the following message by runnin MWoffliner
```
(node:13) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
```

### PR DESCRIPTION
**Pull request by VadimKovalenkoSNF**
Superseeds #1851
Fixes #1840

1. Migrate S3 module to aws sdk for js v3.
2. Add proper error handling.
3. Refactor S3 unit tests.

### CODE REVIEW

**Comment by VadimKovalenkoSNF** [comment]
This PR expect for CI fix here: https://github.com/openzim/mwoffliner/pull/1862

**Review by kelson42 — COMMENTED** [review]
LGTM (at high level) and seems to work but I'm worried about two new errors during `npm i` which seem to have appeared with this PR:
```
> mwoffliner@1.13.0 build
> ./dev/build.sh

Building at [Do 27 Jul 2023 20:34:36 CEST]
node_modules/@types/imagemin-gifsicle/index.d.ts:7:24 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("imagemin")' call instead.

7 import { Plugin } from 'imagemin';
                         ~~~~~~~~~~

node_modules/@types/imagemin-webp/index.d.ts:7:24 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("imagemin")' call instead.

7 import { Plugin } from 'imagemin';
                         ~~~~~~~~~~


Found 2 errors in 2 files.

Errors  Files
     1  node_modules/@types/imagemin-gifsicle/index.d.ts:7
     1  node_modules/@types/imagemin-webp/index.d.ts:7
Build Complete at [Do 27 Jul 2023 20:34:48 CEST]
```
Can we fix them?

I'm surprised the CI goes through with such a severe error during the installation process. Wouldn't that be appropriate to die/stop the CI on such scenarios?

**Comment by kelson42** [comment]
@VadimKovalenkoSNF Please fix the rebase conflict as well.

**Comment by VadimKovalenkoSNF** [comment]
TypeScript error (TS1479) highlighted here: https://github.com/microsoft/TypeScript/issues/54523

**Comment by kelson42** [comment]
@VadimKovalenkoSNF Do you want me to redo the review? If "yes" please request a new review on Github (see the icon for that on Github). Otherwise, why the codecov goes back? Is the PR fully tested (then it should not go back!)?

**Comment by VadimKovalenkoSNF** [comment]
I'll try to increase test coverage here.

**Comment by VadimKovalenkoSNF** [comment]
@kelson42 For some reason codecov marks almost everything in S3 module as uncovered, see https://app.codecov.io/gh/openzim/mwoffliner/pull/1865/blob/src/S3.ts
But methods for this class has been already tested [here](https://github.com/openzim/mwoffliner/blob/7e65e0db19d715dc5cc7ad42a20287943cf014d5/test/unit/s3.test.ts)

**Comment by kelson42** [comment]
@VadimKovalenkoSNF We better clarify this... otherwise no way to trust codecov

**Comment by VadimKovalenkoSNF** [comment]
@kelson42 I noticed that test coverage of S3 equals to zero during build stage, see - https://github.com/openzim/mwoffliner/actions/runs/5693400834/job/15432418757#step:7:622

I noticed the same issue in another PR, check - https://github.com/openzim/mwoffliner/actions/runs/5684250388/job/15406524636#step:7:677

**Comment by VadimKovalenkoSNF** [comment]
> @kelson42 I noticed that test coverage of S3 equals to zero during build stage, see - https://github.com/openzim/mwoffliner/actions/runs/5693400834/job/15432418757#step:7:622
> 
> I noticed the same issue in another PR, check - https://github.com/openzim/mwoffliner/actions/runs/5684250388/job/15406524636#step:7:677

Upd: I was wrong, it seems that the correct report related to S3 is here - https://github.com/openzim/mwoffliner/actions/runs/5693400834/job/15432418757#step:7:221

**Comment by VadimKovalenkoSNF** [comment]
I compared test coverage for S3 between `main` and `aws-sdk-jsv3-migration` branch.

Git branch | File | % Stmts  | % Branch | % Funcs | % Lines |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| aws-sdk-jsv3-migration [report](https://github.com/openzim/mwoffliner/actions/runs/5693400834/job/15432418757#step:7:221)  | S3.ts  | 81.25  | 78.57  | 86.36 | 81.25 |
| main [report](https://github.com/openzim/mwoffliner/actions/runs/5684111964/job/15406105400#step:7:240)  | S3.ts  | 82.35  | 71.42 | 93.75  | 82.35 |

As you can see, function coverage decreased, but this happened because I've introduced a private method `setRegion()` to get a region of S3 bucket (this wasn't needed in the prev aws-sdk version). I did so to hide implementation details, but on the other hand, test coverage for conditions increased. Given this information, I assume, that this PR can be approved.

**Pull request merged**
