### PR TITLE
Convert S3 response body from IncomingMessage object to Buffer

### PR DESCRIPTION
**Pull request by VadimKovalenkoSNF**
Fixes https://github.com/openzim/mwoffliner/issues/1904

### CODE REVIEW

**Comment by kelson42** [comment]
@VadimKovalenkoSNF I test with `./node_modules/.bin/ts-node-esm ./src/cli.ts --adminEmail=kelson@kiwix.org --osTmpDir=/dev/shm --optimisationCacheUrl=http://s3.us-west-1.wasabisys.com/?bucketName=org-kiwix-dev-mwoffliner&keyId=.......&secretAccessKey=...... --mwUrl=https://bm.wikipedia.org --verbose`

This should run on my computer in around 90s.... after minutes, somehow the scrape process seems more or less stuck (maybe just super slow downloading the pictures).

I get also a bunch of S3 errors which are new to me and looks suspicious:
```
[log] [2023-09-13T18:51:56.961Z] Error: The specified key upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Combretum_collinum_Bild0860.jpg/300px-Combretum_collinum_Bild0860.jpg does not exist.
[log] [2023-09-13T18:51:56.978Z] Error: The specified key upload.wikimedia.org/wikipedia/commons/thumb/2/22/Trigonoceps_occipitalis_-Kruger_National_Park%2C_South_Africa_-flying-8.jpg/300px-Trigonoceps_occipitalis_-Kruger_National_Park%2C_South_Africa_-flying-8.jpg does not exist.
[log] [2023-09-13T18:51:56.981Z] Error: The specified key upload.wikimedia.org/wikipedia/commons/thumb/0/09/Dichrostachys_cinerea_0014.jpg/300px-Dichrostachys_cinerea_0014.jpg does not exist.
[log] [2023-09-13T18:51:57.204Z] Error: The specified key upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Red_billed_firefinch_mbweya.jpg/300px-Red_billed_firefinch_mbweya.jpg does not exist.
[log] [2023-09-13T18:51:57.277Z] Error: The specified key upload.wikimedia.org/wikipedia/commons/thumb/4/49/Borassus_aethiopum_MS_4049.jpg/300px-Borassus_aethiopum_MS_4049.jpg does not exist.
[info] [2023-09-13T18:51:57.278Z] Downloading [https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Amsterdam-3174-Muntplein-2008-gje.jpg/120px-Amsterdam-3174-Muntplein-2008-gje.jpg]
[log] [2023-09-13T18:51:57.321Z] Error: The specified key upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Bobgunnia_madagascariensis%2C_sade_en_peul-fragment%2C_Shamvura%2C_a.jpg/300px-Bobgunnia_madagascariensis%2C_sade_en_peul-fragment%2C_Shamvura%2C_a.jpg does not exist.
[log] [2023-09-13T18:51:57.396Z] Progress downloading files [130/1540] [8.4%]
[warn] [2023-09-13T18:51:57.396Z] Error downloading file [https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Seal_of_Mauritania_%28December_2018%29.svg/125px-Seal_of_Mauritania_%28December_2018%29.svg.png], skipping
[log] [2023-09-13T18:51:57.764Z] Error: The specified key upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Ximenia_americana_leaves_%26_fruit_at_Chilkur_near_Hyderabad%2C_AP_W2_IMG_7288.jpg/300px-Ximenia_americana_leaves_%26_fruit_at_Chilkur_near_Hyderabad%2C_AP_W2_IMG_7288.jpg does not exist.
[log] [2023-09-13T18:51:57.766Z] Error: The specified key upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Upupa_epops_Madrid_02.jpg/300px-Upupa_epops_Madrid_02.jpg does not exist.
```

**Comment by VadimKovalenkoSNF** [comment]
@kelson42 , these errors appear because I enabled them while migrating to AWS SDK JS v3, see [here](https://github.com/openzim/mwoffliner/pull/1865/files#diff-ffba4109e032a678ef88c66052d1b5e5cb4f638897dd6c50f8cc20a525c1ca1fR108). In comparison, previous version of AWS SDK just omitted this error (see[ this line](https://github.com/openzim/mwoffliner/blob/040b9c6add4339e3422d1c4ae085dc3187e2392d/src/S3.ts#L74) in the prev implementation). I've checked prev version, and some images indeed didn't download and the error did not appear (I've intercepted this only by manual logging). My opinion is that we need to keep this error handler to have explicit info about image download process.

**Comment by VadimKovalenkoSNF** [comment]
>The problem here is not the logging, the problem is why we request a content which is not here?

Regarding[ the condition ](https://github.com/openzim/mwoffliner/blob/main/src/Downloader.ts#L516) of the S3 download invocation, we do so because we expect these images are present in the bucket already. We don't know whether image exist till send the request to the S3 bucket first.

**Review by kelson42 — APPROVED** [review]
LGTM

**Pull request merged**
